name    'mkrakowitzer-deploy'
version '0.0.2'
source 'https://github.com/mkrakowitzer/puppet-deploy.git'
author 'mkrakowitzer'
license 'Apache License, Version 2.0'
summary 'Puppet module to deploy tar files'
description 'Puppet module to deploy tar files'
project_page 'https://github.com/mkrakowitzer/puppet-deploy'
